export const ProductDummyData = [
  {
    id: 1,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 500000,
    productCrossedOutPrice: 560000,
    productImage: "/assets/images/iphone-14.png",
  },
  {
    id: 2,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 670000,
    productCrossedOutPrice: 990000,
    productImage: "/assets/images/airpod.png",
  },
  {
    id: 3,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 240000,
    productCrossedOutPrice: 990000,
    productImage: "/assets/images/shoe.png",
  },
  {
    id: 4,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 540000,
    productCrossedOutPrice: 890000,
    productImage: "/assets/images/headset.png",
  },
  {
    id: 5,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 890000,
    productCrossedOutPrice: 100000,
    productImage: "/assets/images/ipad.png",
  },
  {
    id: 6,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 290000,
    productCrossedOutPrice: 130000,
    productImage: "/assets/images/suit.png",
  },
  {
    id: 7,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 490000,
    productCrossedOutPrice: 430000,
    productImage: "/assets/images/speaker.png",
  },
  {
    id: 8,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 330000,
    productCrossedOutPrice: 770000,
    productImage: "/assets/images/ps4-picture.png",
  },
  {
    id: 9,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 330000,
    productCrossedOutPrice: 770000,
    productImage: "/assets/images/smart-tv.png",
  },
  {
    id: 10,
    productName: "Skullcandy Indy True Wireless",
    productPrice: 330000,
    productCrossedOutPrice: 770000,
    productImage: "/assets/images/smart-watch.png",
  },
];
