export const ShopData = [
  {
    id: 1,
    store_owner: "Grando Store",
    product_name: "Men's Canvas Breathable Sports Casual Running Shoes -blue",
    review: 5,
    product_image: "/assets/images/house02.jpg",
    crossed_out_price: 650000,
    price: 50000,
    one_star: 55,
    two_star: 45,
    three_star: 49,
    four_star: 30,
    five_star: 29,
  },
  {
    id: 2,
    store_owner: "Grando Store",
    product_name: "Women's Canvas Breathable Sports Casual Running Shoes -red",
    product_image: "/assets/images/house02.jpg",
    review: 4,
    crossed_out_price: 550000,
    price: 60000,
    one_star: 25,
    two_star: 65,
    three_star: 43,
    four_star: 23,
    five_star: 93,
  },
  {
    id: 3,
    store_owner: "Grando Store",
    product_image: "/assets/images/house02.jpg",
    product_name: "Men's Leather Breathable Sports Casual Running Shoes -black",
    review: 2,
    crossed_out_price: 350000,
    price: 40000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 4,
    store_owner: "Grando Store",
    product_name: "Kids' Canvas Breathable Sports Casual Running Shoes -green",
    product_image: "/assets/images/house02.jpg",
    review: 3,
    crossed_out_price: 450000,
    price: 50000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 5,
    store_owner: "Grando Store",
    product_name: "Men's Leather Breathable Sports Casual Running Shoes -black",
    product_image: "/assets/images/house02.jpg",
    review: 2,
    crossed_out_price: 350000,
    price: 40000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 6,
    store_owner: "Grando Store",
    product_name: "Women's Canvas Breathable Sports Casual Running Shoes -red",
    product_image: "/assets/images/house02.jpg",
    review: 4,
    crossed_out_price: 550000,
    price: 60000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 7,
    store_owner: "Grando Store",
    product_name: "Women's Leather Breathable Sports Casual Running Shoes -white",
    product_image: "/assets/images/house02.jpg",
    review: 1,
    crossed_out_price: 250000,
    price: 30000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 8,
    store_owner: "Grando Store",
    product_name: "Women's Leather Breathable Sports Casual Running Shoes -white",
    product_image: "/assets/images/house02.jpg",
    review: 1,
    crossed_out_price: 250000,
    price: 30000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 9,
    store_owner: "Grando Store",
    product_name: "Women's Canvas Breathable Sports Casual Running Shoes -red",
    product_image: "/assets/images/house02.jpg",
    review: 4,
    crossed_out_price: 550000,
    price: 60000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
  {
    id: 10,
    store_owner: "Grando Store",
    product_name: "Kids' Canvas Breathable Sports Casual Running Shoes -green",
    product_image: "/assets/images/house02.jpg",
    review: 3,
    crossed_out_price: 450000,
    price: 50000,
    one_star: 15,
    two_star: 45,
    three_star: 53,
    four_star: 65,
    five_star: 93,
  },
];
